Rename doctr file to expected filename.
Test on master fail as the encrypted filename expected does not match:

> FileNotFoundError: [Errno 2] No such file or directory: 'github_deploy_key_deshaw_pyflyby.enc'

Is that due to the repository being moved at some point in the past ?